### PR TITLE
Fix Session param decorator missing options

### LINKED ISSUE #140: Rationale for not supporting "required" session params?
It seems like `@Session(<param>, { required: <true|false> })` should work to be consistent with `@Param`, `@QueryParam`, `@Body`, etc.

I can maybe understand why `@Session({ required: false })` isn't supported, but even so I think it's unnecessarily opinionated to not support the `required` option on session params.

### PR DESCRIPTION
**Pull request by 19majkel94**
Fixes #140.

### CODE REVIEW

File: src/decorator/Session.ts [hunk 1]
```diff
@@ -1,20 +1,39 @@
...
+export function Session(propertyName: string, options?: ParamOptions): ParameterDecorator;
+
+export function Session(optionsOrObjectName?: ParamOptions|string, paramOptions?: ParamOptions): ParameterDecorator {
+    let propertyName: string|undefined;
+    let options: ParamOptions|undefined;
+    if (typeof optionsOrObjectName === "string") {
+        propertyName = optionsOrObjectName;
+        options = paramOptions || {};
+    } else {
+        options = optionsOrObjectName || {};
```
Comment (marshall007) [inline src/decorator/Session.ts]: @19majkel94 based on the conversation in #140 I thought we decided it didn't make sense to support `@Session({ required: false})`, which I think this would allow you to do now.

Comment (19majkel94) [inline src/decorator/Session.ts]: Yeah, I know but I think that default `true` is enough. If someone want to hurt himself, it will allow to do it 😉
