### PR TITLE
Fix not working validationOptions and it's type

### LINKED ISSUE #102: ValidationOptions has no property skipMissingProperties?
I am using routing-controllers with typescript.
I  want to use skipMissingProperties when I use createExpressServer method.
But, skipMissingProperties  does not in  ValidationOptions ，as fllows.
```
/**
 * Options used to pass to validation decorators.
 */
export interface ValidationOptions {
    /**
     * Specifies if validated value is an array and each of its item must be validated.
     */
    each?: boolean;
    /**
     * Error message used to be used on validation fail.
     * You can use "$value" to use value that was failed by validation.
     * You can use "$constraint1" and "$constraint2" keys in the message string,
     * and they will be replaced with constraint values if they exist.
     * Message can be either string, either a function that returns a string.
     * Second option allows to use values and custom messages depend of them.
     */
    message?: string | ((value?: any, constraint1?: any, constraint2?: any) => string);
    /**
     * Validation groups used for this validation.
     */
    groups?: string[];
    /**
     * Indicates if validation must be performed always, no matter of validation groups used.
     */
    always?: boolean;
}
```

How to solve this problem ?  thanks

### PR DESCRIPTION
**Pull request by 19majkel94**
Fixed #102.

### CODE REVIEW

File: src/RoutingControllersOptions.ts [hunk 1]
```diff
@@ -55,7 +55,7 @@ export interface RoutingControllersOptions {
     /**
      * Global class-validator options passed during validate operation.
      */
-    validationOptions?: ValidationOptions;
+    validationOptions?: ValidatorOptions;
```
Comment (pleerock) [inline src/RoutingControllersOptions.ts]: I don't like `ValidationOptions` and `ValidationOptions` in class-validator package. Good to rename then however I didnt find a good name for both when was creating them

**Comment by pleerock** [comment]
thank you)
